# Generated by Django 4.2.6 on 2023-10-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfuser',
            name='handicap',
        ),
        migrations.RemoveField(
            model_name='golfuser',
            name='height',
        ),
        migrations.RemoveField(
            model_name='golfuser',
            name='player_image',
        ),
        migrations.RemoveField(
            model_name='golfuser',
            name='sensor_id',
        ),
    ]
